# Generated by Django 3.2.5 on 2021-09-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_address_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Payment'},
        ),
    ]
