# Generated by Django 3.2.5 on 2021-09-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_shippingaddress_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
